#!/usr/bin/python

import sys
import os
import signal
import functools
import logging
import asyncio
import socket
import subprocess
import systemd.journal
import systemd.daemon
import argparse
import shlex


class QrexecConnect:
    """A systemd-native qrexec-client-vm service

    Attributes
    ----------
    exit_signals: tuple[str]
        A list of signal names that should stop the application

    NO_LISTEN_FDS: int
        Return code when not started as a systemd service

    UNSUPPORTED_ADDRESS_FAMILY: int
        Return code when socket fd is not one of IPv4, IPv6, or Unix

    FILEDESCRIPTORNAME_ERROR: int
        Return code when FileDescriptorName value is not exactly two arguments
    """

    exit_signals = ("SIGINT", "SIGTERM")

    NO_LISTEN_FDS = 125
    UNSUPPORTED_ADDRESS_FAMILY = 126
    FILEDESCRIPTORNAME_ERROR = 127

    def __init__(self):
        """Parses arguments, sets up logging, and tests for listening fds provided by systemd"""

        arg_parser = argparse.ArgumentParser(
            description="%(prog)s: systemd-native qrexec-client-vm",
        )
        arg_parser.add_argument("--buffer-size", type=int, default=65536)
        arg_parser.add_argument("-d", "--debug", action="store_true")

        self.logger = logging.getLogger(arg_parser.prog)
        self.logger.addHandler(
            systemd.journal.JournalHandler(SYSLOG_IDENTIFIER=arg_parser.prog)
        )

        args = arg_parser.parse_args()
        self.buffer_size = args.buffer_size
        self.debug = args.debug

        if self.debug:
            self.logger.setLevel(logging.DEBUG)
        else:
            self.logger.setLevel(logging.INFO)

        self.fds_with_names = systemd.daemon.listen_fds_with_names()

        if not self.fds_with_names:
            print("No listen FDs found", file=sys.stderr)
            exit(self.NO_LISTEN_FDS)

    async def run(self):
        """Run connection servers"""

        loop = asyncio.get_running_loop()

        for signame in self.exit_signals:
            qrexec_connect_exit = functools.partial(self.exit, signame, loop)

            loop.add_signal_handler(
                getattr(signal, signame),
                qrexec_connect_exit,
            )

        systemd.daemon.notify("READY=1")

        async with asyncio.TaskGroup() as connection_server_group:
            for fd, fd_name in self.fds_with_names.items():
                connection_server_group.create_task(self.serve_connection(fd, fd_name))

    def exit(self, signame, loop):
        """Gracefully exits in response to signals

        Parameters
        ----------
        signame: str
            Signal name, like "SIGINT"

        loop: asyncio.EventLoop
            Running event loop
        """
        systemd.daemon.notify("STOPPING=1")
        loop.stop
        exit(0)

    async def serve_connection(self, fd, fd_name):
        """Start asyncio connection server from systemd socket and qrexec-client-vm arguments

        Parameters
        ----------
        fd: int
            Listening systemd socket file descriptor

        fd_name: str
            FileDescriptorName value for systemd socket
        """
        sock = socket.socket(fileno=fd)
        target_qube, rpc_service = self.parse_fd_name(fd_name)

        # functools.partial can't generate async functions, yet
        async def handle_connection(reader, writer):
            await self.qrexec_handle_connection(
                target_qube, rpc_service, reader, writer
            )

        if sock.family in (socket.AF_INET, socket.AF_INET6):
            server = await asyncio.start_server(handle_connection, sock=sock)
        elif sock.family == socket.AF_UNIX:
            server = await asyncio.start_unix_server(handle_connection, sock=sock)
        else:
            print(f"Unsupported address family: {sock.family}", file=sys.stderr)
            exit(self.UNSUPPORTED_ADDRESS_FAMILY)

        self.logger.info(
            f"{sock.getsockname()}: {shlex.join((target_qube, rpc_service))}"
        )

        async with server:
            await server.serve_forever()

    def parse_fd_name(self, fd_name):
        """Parse systemd FileDescriptorName value

        Parameters
        ----------
        fd_name: str
            FileDescriptorName value for systemd socket

        Returns
        -------
        array[str]
            An array of strings containing arguments to qrexec-client-vm
        """
        argv = shlex.split(fd_name)

        if len(argv) != 2:
            print(
                f'{sock.getsockname()}: FileDescriptorName takes 2 arguments but {len(argv)} {"was" if len(argv) == 1 else "were"} given',
                file=sys.stderr,
            )
            exit(self.FILEDESCRIPTORNAME_ERROR)

        return argv

    async def qrexec_handle_connection(self, target_qube, rpc_service, reader, writer):
        """Handle client qube connections to a listening socket

        Parameters
        ----------
        target_qube: str
            Service qube

        rpc_service: str
            Qube RPC service descriptor (rpc_name[+rpc_arg])

        reader: asyncio.StreamReader
            Input stream generated by asyncio.start_[unix_]server

        writer: asyncio.StreamWriter
            Output stream generated by asyncio.start_[unix_]server
        """
        qrexec_client = await asyncio.create_subprocess_exec(
            "/usr/bin/qrexec-client-vm",
            f"--buffer-size={self.buffer_size}",
            "--no-filter-escape-chars-stdout",
            "--filter-escape-chars-stderr",
            "--",
            target_qube,
            rpc_service,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )

        async with asyncio.TaskGroup() as qrexec_client_group:
            qrexec_client_group.create_task(qrexec_client.wait())
            qrexec_client_group.create_task(
                self.qrexec_pipe(reader, qrexec_client.stdin)
            )
            qrexec_client_group.create_task(
                self.qrexec_pipe(qrexec_client.stdout, writer)
            )

        if qrexec_client.returncode != 0:
            if rpc_arg:
                rpc_service = "+".join((rcp_name, rpc_arg))
            else:
                rpc_service = rpc_name

            stderr = await qrexec_client.stderr.read(self.buffer_size)
            error_message = stderr.decode("ascii")

            fd_name = shlex.join((target_qube, rpc_service))
            self.logger.warning(f"{fd_name}: {error_message}")

    async def qrexec_pipe(self, source, sink):
        """Pipe data from source stream to sink stream until source reaches EOF

        Parameters
        ----------
        source: asyncio.StreamReader
            Input stream

        sink: asyncio.StreamWriter
            Output stream
        """
        while not source.at_eof():
            data = await source.read(self.buffer_size)
            if data:
                sink.write(data)
                await sink.drain()
            else:
                source.feed_eof()

        sink.close()
        await sink.wait_closed()


if __name__ == "__main__":
    asyncio.run(QrexecConnect().run())
